from __future__ import annotations

import json
import uuid
from typing import Literal

from fastapi import FastAPI, HTTPException
from ollama import chat
from pydantic import BaseModel, Field

from space_registry import resolve_route

from pathlib import Path
from fastapi.responses import FileResponse

BASE_DIR = Path(__file__).resolve().parent


# =========================================================
# Configuration
# =========================================================

OLLAMA_MODEL = "gemma3:1b"


app = FastAPI(
    title="Space Intention Encoder and Switch",
    version="0.2",
)


# =========================================================
# Incoming API request
# =========================================================

class EncodeRequest(BaseModel):
    message: str = Field(min_length=1)


# =========================================================
# Information generated by the AI
# =========================================================

class ParsedTarget(BaseModel):
    type: Literal["order", "unknown"]
    id: str | None = None


class ParsedIntent(BaseModel):
    action: Literal[
        "check_order_status",
        "cancel_order",
        "unsupported",
    ]

    target: ParsedTarget

    requested_output: list[
        Literal[
            "current_status",
            "estimated_delivery",
            "tracking_number",
        ]
    ] = Field(default_factory=list)

    needs_clarification: bool = False
    clarification_question: str | None = None


# =========================================================
# Route selected from the Space Registry
# =========================================================

class SelectedRoute(BaseModel):
    space_id: str
    endpoint: str


# =========================================================
# Final protocol message
# =========================================================

class ProtocolMessage(BaseModel):
    protocol: Literal["space/0.1"]
    message_type: Literal["REQUEST"]
    task_id: str

    sender: str
    receiver: str

    action: Literal[
        "check_order_status",
        "cancel_order",
    ]

    target: ParsedTarget
    requested_output: list[str]


# Returned while developing so we can inspect each stage.
class RoutingResult(BaseModel):
    parsed_intent: ParsedIntent
    selected_route: SelectedRoute
    protocol_message: ProtocolMessage


# =========================================================
# Step 1A: AI intention encoding
# =========================================================

def interpret_intention(message: str) -> ParsedIntent:
    """
    Convert natural language into one validated structured intention.
    """

    schema = ParsedIntent.model_json_schema()

    response = chat(
        model=OLLAMA_MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "Convert the user's message into exactly one structured "
                    "Space protocol intention.\n\n"

                    "Supported actions:\n"
                    "- check_order_status\n"
                    "- cancel_order\n\n"

                    "Action rules:\n"
                    "- Use check_order_status when the user asks where an "
                    "order is, asks for its status, delivery time, or "
                    "tracking number.\n"
                    "- Use cancel_order when the user asks to cancel an "
                    "order.\n"
                    "- If the user asks for more than one action, use "
                    "unsupported.\n"
                    "- Use unsupported for any action not listed above.\n\n"

                    "Target rules:\n"
                    "- Extract the exact order ID written by the user.\n"
                    "- Never invent an order ID.\n"
                    "- If an order ID is present, never say it is missing.\n"
                    "- For supported order actions, target.type must be "
                    "'order'.\n"
                    "- For unsupported actions, target.type may be "
                    "'unknown'.\n\n"

                    "Clarification rules:\n"
                    "- Set needs_clarification to true only when the user "
                    "requests exactly one supported action but does not "
                    "provide an order ID.\n"
                    "- Do not request clarification for unsupported actions.\n\n"

                    "Requested-output rules:\n"
                    "- For check_order_status, include current_status.\n"
                    "- Include estimated_delivery when the user asks when "
                    "the order will arrive.\n"
                    "- Include tracking_number when the user requests "
                    "tracking information.\n"
                    "- For cancel_order, requested_output must be empty.\n\n"

                    "Return only data matching the supplied JSON schema."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"User message:\n{message}\n\n"
                    f"Required JSON schema:\n"
                    f"{json.dumps(schema)}"
                ),
            },
        ],
        format=schema,
        options={
            "temperature": 0,
        },
    )

    response_content = response.message.content

    if not response_content:
        raise ValueError(
            "The local model returned an empty response."
        )

    return ParsedIntent.model_validate_json(
        response_content
    )


# =========================================================
# Step 1B: Deterministic output normalization
# =========================================================

def normalize_requested_output(
    original_message: str,
    intent: ParsedIntent,
) -> ParsedIntent:
    """
    Validate and correct requested_output using the original message.

    The local AI determines the main action and target. This function
    ensures obvious requested outputs are not accidentally omitted.
    """

    # Cancellation does not request order information.
    if intent.action == "cancel_order":
        intent.requested_output = []
        return intent

    # Unsupported actions should not contain requested outputs.
    if intent.action == "unsupported":
        intent.requested_output = []
        return intent

    message_lower = original_message.lower()

    # Every order-status request should return the current status.
    requested_output: list[str] = [
        "current_status"
    ]

    delivery_phrases = [
        "when it will arrive",
        "when will it arrive",
        "when is it arriving",
        "when it arrives",
        "arrival date",
        "arrival",
        "arrive",
        "delivery date",
        "delivery time",
        "estimated delivery",
    ]

    tracking_phrases = [
        "tracking number",
        "tracking information",
        "tracking details",
        "track my order",
        "track the order",
        "tracking",
    ]

    if any(
        phrase in message_lower
        for phrase in delivery_phrases
    ):
        requested_output.append(
            "estimated_delivery"
        )

    if any(
        phrase in message_lower
        for phrase in tracking_phrases
    ):
        requested_output.append(
            "tracking_number"
        )

    intent.requested_output = requested_output

    return intent


# =========================================================
# Step 2: Intent switching
# =========================================================

def switch_intention(
    intent: ParsedIntent,
) -> SelectedRoute:
    """
    Use the structured action to select a receiving Space.
    """

    route = resolve_route(intent.action)

    return SelectedRoute(
        space_id=route["space_id"],
        endpoint=route["endpoint"],
    )


# =========================================================
# Build the trusted protocol message
# =========================================================

def build_protocol_message(
    intent: ParsedIntent,
    route: SelectedRoute,
) -> ProtocolMessage:
    """
    Add trusted protocol information after the intention has
    been interpreted and the destination has been selected.
    """

    if intent.action not in {
        "check_order_status",
        "cancel_order",
    }:
        raise ValueError(
            f"Cannot build a protocol message for "
            f"action '{intent.action}'."
        )

    return ProtocolMessage(
        protocol="space/0.1",
        message_type="REQUEST",
        task_id=f"task-{uuid.uuid4()}",
        sender="space://aiden",
        receiver=route.space_id,
        action=intent.action,
        target=intent.target,
        requested_output=intent.requested_output,
    )


# =========================================================
# API routes
# =========================================================

@app.get("/", include_in_schema=False)
def frontend():
    return FileResponse(BASE_DIR / "space_frontend.html")


@app.get("/style.css", include_in_schema=False)
def stylesheet():
    return FileResponse(
        BASE_DIR / "style.css",
        media_type="text/css"
    )


@app.get("/health")
def health():
    return {
        "name": "Space Intention Encoder and Switch",
        "version": "0.2",
        "status": "online"
    }


@app.post(
    "/route-intent",
    response_model=RoutingResult,
)
@app.post(
    "/encode-intent",
    response_model=RoutingResult,
)
def route_intent(
    request: EncodeRequest,
) -> RoutingResult:
    # -----------------------------------------------------
    # Step 1: Interpret and normalize the intention
    # -----------------------------------------------------

    try:
        intent = interpret_intention(
            request.message
        )

        intent = normalize_requested_output(
            original_message=request.message,
            intent=intent,
        )

    except Exception as error:
        raise HTTPException(
            status_code=502,
            detail=(
                f"Could not interpret intention: "
                f"{error}"
            ),
        ) from error

    # -----------------------------------------------------
    # Validate the interpreted intention
    # -----------------------------------------------------

    if intent.action == "unsupported":
        raise HTTPException(
            status_code=422,
            detail={
                "error": "unsupported_action",
                "message": (
                    "The request contains an unsupported "
                    "action or more than one action."
                ),
            },
        )

    if (
        intent.needs_clarification
        or intent.target.type != "order"
        or not intent.target.id
    ):
        raise HTTPException(
            status_code=422,
            detail={
                "error": "clarification_required",
                "question": (
                    intent.clarification_question
                    or "Which order should be used?"
                ),
            },
        )

    # -----------------------------------------------------
    # Step 2: Select the receiving Space
    # -----------------------------------------------------

    try:
        selected_route = switch_intention(
            intent
        )

    except LookupError as error:
        raise HTTPException(
            status_code=404,
            detail={
                "error": "route_not_found",
                "message": str(error),
            },
        ) from error

    # -----------------------------------------------------
    # Construct the trusted protocol message
    # -----------------------------------------------------

    try:
        protocol_message = build_protocol_message(
            intent=intent,
            route=selected_route,
        )

    except ValueError as error:
        raise HTTPException(
            status_code=422,
            detail={
                "error": "invalid_protocol_message",
                "message": str(error),
            },
        ) from error

    return RoutingResult(
        parsed_intent=intent,
        selected_route=selected_route,
        protocol_message=protocol_message,
    )